server:
  type: ftp
  ftp:
    host:
    port: 21
    username:
    password:
    sources:
      - /
    timeout: 5s
    disable_epsv: false
    tls: false
    insecure_skip_verify: false
    log_trace: false

db:
  enable: true
  path: ftpgrab.db

download:
  output: /download
  uid:
  gid:
  chmod_file: 0644
  chmod_dir: 0755
  include:
  exclude:
  since: 0001-01-01T00:00:00Z
  retry: 3
  hide_skipped: false
  create_basedir: false

notif:
  mail:
    enable: false
    host: localhost
    port: 25
    ssl: false
    insecure_skip_verify: false
    username:
    password:
    from:
    to:
  webhook:
    enable: false
    endpoint:
    method: GET
    headers: {}
    timeout: 10s
